import 'dotenv/config';
import typescript from '@rollup/plugin-typescript';
import {nodeResolve} from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import copy from 'rollup-plugin-copy-watch'

const isProd = (process.env.BUILD === 'production');
const outdir = process.env.OBSIDIAN_PLUGIN_DIR || './dist/';

const banner = 
`/*
THIS IS A GENERATED/BUNDLED FILE BY ROLLUP
if you want to view the source visit the plugins github repository
*/
`;

export default {
  input: './src/main.ts',
  output: {
    dir: outdir,
    sourcemap: isProd ? 'hidden' : 'inline',
    sourcemapExcludeSources: isProd,
    format: 'cjs',
    exports: 'default',
    banner,
  },
  external: ['obsidian'],
  plugins: [
    typescript(),
    nodeResolve({browser: true}),
    commonjs(),
    copy({
      watch: ["styles.css", "manifest*.json"],
      targets: [
        { src: 'manifest.json', dest: outdir },
        { src: 'manifest-beta.json', dest: outdir },
        { src: 'styles.css', dest: outdir }
      ], flatten: false
    })
  ]
};